/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import domain.Eksperiment;
import domain.VrstaEksperimenta;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import logic.Controller;

/**
 *
 * @author vojislav
 */
public class FrmEksperiment extends javax.swing.JFrame {

    /**
     * Creates new form FrmNoviEksperiment
     */
    Eksperiment eksperiment;
    Controller controller;
    public FrmEksperiment(Eksperiment eksperiment, Controller controller, boolean flag) {
        initComponents();
        this.controller = controller;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            controller.setFrmEksperiment(this);
        } catch (Exception ex) {
            Logger.getLogger(FrmEksperiment.class.getName()).log(Level.SEVERE, null, ex);
        }
        populateFields(eksperiment, flag);
        this.eksperiment = eksperiment;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNaslov = new javax.swing.JLabel();
        txtNazivEksperimenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpisEksperimenta = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtKorisceneSupstance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbVrstaEksp = new javax.swing.JComboBox<>();
        btnKreiraj = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv eksperimenta");

        lblNaslov.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNaslov.setText("Kreiranje eksperimenta");

        jLabel3.setText("Opis Eksperimenta");

        txtOpisEksperimenta.setColumns(20);
        txtOpisEksperimenta.setRows(5);
        jScrollPane1.setViewportView(txtOpisEksperimenta);

        jLabel4.setText("Korišćene supstance");

        jLabel5.setText("Vrsta eksperimenta");

        cbVrstaEksp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbVrstaEksp.setSelectedIndex(-1);

        btnKreiraj.setText("Kreiraj novi eksperiment");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtKorisceneSupstance)
                    .addComponent(jScrollPane1)
                    .addComponent(txtNazivEksperimenta)
                    .addComponent(cbVrstaEksp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(lblNaslov)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNaslov)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNazivEksperimenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKorisceneSupstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVrstaEksp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreiraj)
                    .addComponent(btnOtkazi))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        eksperiment.setNaziv(txtNazivEksperimenta.getText());
        eksperiment.setOpis(txtOpisEksperimenta.getText());
        eksperiment.setKorisceneSupstance(txtKorisceneSupstance.getText());
        eksperiment.setVrstaEksperimenta( (VrstaEksperimenta) cbVrstaEksp.getSelectedItem());
        
        if(eksperiment.getNaziv().isEmpty()||eksperiment.getNaziv().length()>100){
            JOptionPane.showMessageDialog(this, "Naziv je neispravan");
        }
        else if(eksperiment.getOpis().isEmpty()||eksperiment.getOpis().length()>255){
            JOptionPane.showMessageDialog(this, "Opis je neispravan");
        }
        else if(eksperiment.getKorisceneSupstance().isEmpty()||eksperiment.getKorisceneSupstance().length()>255){
            JOptionPane.showMessageDialog(this, "Koriscene supsatnce su neispravne");
        }
        else if(eksperiment.getVrstaEksperimenta()==null){
            JOptionPane.showMessageDialog(this, "Selektujte vrstu eksperimenta");
        }
        else{
            ubaciUBazu(eksperiment);
        }
        
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox<Object> cbVrstaEksp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JTextField txtKorisceneSupstance;
    private javax.swing.JTextField txtNazivEksperimenta;
    private javax.swing.JTextArea txtOpisEksperimenta;
    // End of variables declaration//GEN-END:variables

    private void populateFields(Eksperiment eksperiment, boolean flag) {
        txtOpisEksperimenta.setLineWrap(true);
        txtOpisEksperimenta.setWrapStyleWord(true);
        cbVrstaEksp.setModel(new DefaultComboBoxModel(VrstaEksperimenta.values()));
        
        txtOpisEksperimenta.setEditable(flag);
        txtNazivEksperimenta.setEditable(flag);
        txtKorisceneSupstance.setEditable(flag);
        cbVrstaEksp.setEnabled(flag);
        btnKreiraj.setVisible(flag);
        
        
        if(eksperiment.getId()!=0){
            lblNaslov.setText("Izmena eksperimenta");
            if(!flag){
            lblNaslov.setText("Detalji eksperimenta");
            }
            txtNazivEksperimenta.setText(eksperiment.getNaziv());
            txtKorisceneSupstance.setText(eksperiment.getKorisceneSupstance());
            txtOpisEksperimenta.setText(eksperiment.getOpis());
            cbVrstaEksp.setSelectedIndex(eksperiment.getVrstaEksperimenta().getId()-1);
            btnKreiraj.setText("Izmeni eksperiment");
        }
        else{
            JOptionPane.showMessageDialog(this, "Sistem je kreirao novi eksperiment");
            cbVrstaEksp.setSelectedIndex(-1);
        }
        
    }

    private void ubaciUBazu(Eksperiment eksperiment) {
        if(eksperiment.getId()==0){
            try {
                controller.kreirajEksperiment(eksperiment);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        
        }else{
            try {
                controller.izmeniEksperiment(eksperiment);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
        
        
    }
    public void kreiranEksperiment(boolean flag) throws Exception{
        if(flag){
            JOptionPane.showMessageDialog(this, "Uspešno dodavanje eksperimenta!");
            Controller.getInstance().setFrmEksperiment(null);
            dispose();
            
        }else{
            JOptionPane.showMessageDialog(this, "Neuspešno dodavanje eksperimenta!");
            Controller.getInstance().setFrmEksperiment(null);
            dispose();
        }
    }
    public void izmenjenEksperiment(boolean flag) throws Exception{
                if(flag){
                    JOptionPane.showMessageDialog(this, "Uspešna izmena eksperimenta!");
                    Controller.getInstance().setFrmEksperiment(null);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Neuspešna izmena eksperimenta!");
                    Controller.getInstance().setFrmEksperiment(null);
                    dispose();
                }
    }
}
