/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Eksperiment;
import domain.Rezultat;
import domain.User;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logic.Controller;
import tablemodel.EksperimentiTableModel;
import tablemodel.RezultatiTableModel;

/**
 *
 * @author vojislav
 */
public class FrmNadlezni extends javax.swing.JFrame {

    /**
     * Creates new form FrmNadlezni
     */
    User korisnik = new User();
    public FrmNadlezni(User user) {
        initComponents();
        
        this.korisnik = user;
        setUp();
       try {
            Controller.getInstance().setFrmNadlezni(this);
        } catch (Exception ex) {
            Logger.getLogger(FrmNadlezni.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
            Controller.getInstance().logout(korisnik);
            
            } catch (Exception ex) {
            
            }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPretraga = new javax.swing.JButton();
        btnIzmena = new javax.swing.JButton();
        btnObjava = new javax.swing.JButton();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezultati = new javax.swing.JTable();
        cbPretraga = new javax.swing.JComboBox<>();
        btnOdjava = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblKorisnik = new javax.swing.JLabel();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPretraga.setText("Pretraga rezultata");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        btnIzmena.setText("Izmena rezultata");
        btnIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaActionPerformed(evt);
            }
        });

        btnObjava.setText("Objavljivanje rezultata");
        btnObjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjavaActionPerformed(evt);
            }
        });

        tblRezultati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRezultati);

        cbPretraga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Naziv Eksperimenta", "Naziv Rezultata", "Opis", "Vrsta Rezultata" }));
        cbPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPretragaActionPerformed(evt);
            }
        });

        btnOdjava.setText("Odjava");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        jLabel2.setText("Pozdrav korisniče pod imenom: ");

        lblKorisnik.setText("jLabel3");

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblKorisnik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPretraga)
                                .addGap(18, 18, 18)
                                .addComponent(cbPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnIzmena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnObjava, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPretraga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetalji, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblKorisnik))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPretraga)
                                .addComponent(cbPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetalji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObjava))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnOdjava)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPretragaActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        try {
            Controller.getInstance().logout(korisnik);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaActionPerformed
        int rowIndex = tblRezultati.getSelectedRow();
        RezultatiTableModel model = (RezultatiTableModel) tblRezultati.getModel();
        Rezultat rezultat = model.getRezultatAt(rowIndex);
        if(rezultat!=null){
            JFrame frmIzmena = new FrmRezultat(rezultat.getEksperiment(),rezultat, true);
            frmIzmena.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Niste selektovali nijedan rezultat! ");
        }
    }//GEN-LAST:event_btnIzmenaActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        String kolona = "";
        if(cbPretraga.getSelectedItem().equals("Naziv Eksperimenta")) kolona = "e.naziv";
        else if(cbPretraga.getSelectedItem().equals("Naziv Rezultata")) kolona = "r.naziv";
        else if(cbPretraga.getSelectedItem().equals("Vrsta Rezultata")) kolona = "Vrsta Rezultata";
        else kolona ="r.opis";
        String kriterijum = txtPretraga.getText();
        String[] argumenti = {kriterijum, kolona};
        
        try {
            Controller.getInstance().pretragaRezultata(argumenti);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnObjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjavaActionPerformed
        int rowIndex = tblRezultati.getSelectedRow();
        RezultatiTableModel model = (RezultatiTableModel) tblRezultati.getModel();
        Rezultat rezultat = model.getRezultatAt(rowIndex);
        if(rezultat!=null){
            FrmObjava frmObjava = new FrmObjava(rezultat);
            frmObjava.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Niste selektovali nijedan rezultat! ");
        }
    }//GEN-LAST:event_btnObjavaActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int rowIndex = tblRezultati.getSelectedRow();
        RezultatiTableModel model = (RezultatiTableModel) tblRezultati.getModel();
        Rezultat rezultat = model.getRezultatAt(rowIndex);
        if(rezultat!=null){
            JFrame frmIzmena = new FrmRezultat(rezultat.getEksperiment(),rezultat, false);
            frmIzmena.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Niste selektovali nijedan rezultat! ");
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnIzmena;
    private javax.swing.JButton btnObjava;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JComboBox<String> cbPretraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKorisnik;
    private javax.swing.JTable tblRezultati;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    public void setUp() {
        lblKorisnik.setText(korisnik.getIme() + " "+korisnik.getPrezime());
        String[] argumenti = {"",""};
         try {
            Controller.getInstance().pretragaRezultata(argumenti);
        } catch (Exception ex) {
            Logger.getLogger(FrmLaborant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void odjava(boolean flag){
        if(flag){
                System.exit(0);
            }else{
                JOptionPane.showMessageDialog(this, "Neuspesno logoutovanje ?");
            }
    }
    public void pretraga(List<Rezultat> rezultati){
        if(!rezultati.isEmpty()){
                tblRezultati.setModel(new RezultatiTableModel(rezultati));
                
            }
            else
                JOptionPane.showMessageDialog(this, "Nema odgovarajucih rezultata na osnovu parametara pretrage!");
    }

    public void close() {
        JOptionPane.showMessageDialog(this, "Server zatvoren...");
        System.exit(0);
    }

    public void poruka(String poruka) {
        JOptionPane.showMessageDialog(this, "Poruka od servera: " + poruka);
    }
}

