/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Eksperiment;
import domain.Rezultat;
import domain.VrstaEksperimenta;
import domain.VrstaRezultata;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logic.Controller;

/**
 *
 * @author vojislav
 */
public class FrmRezultat extends javax.swing.JFrame {

    /**
     * Creates new form FrmRezultat
     */
    Eksperiment eksperiment;
    Rezultat rezultat;
    public FrmRezultat(Eksperiment eksperiment, Rezultat rezultat, boolean flag) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            Controller.getInstance().setFrmRezultat(this);
        } catch (Exception ex) {
            Logger.getLogger(FrmRezultat.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.eksperiment = eksperiment;
        this.rezultat = rezultat;
        setUp(flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNazivRez = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbVrstaRezultata = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnOtkazi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        lblEksperiment = new javax.swing.JLabel();
        cbEksperimenti = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpisRez = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv rezultata");

        jLabel2.setText("Opis rezultata");

        jLabel3.setText("Vrsta rezultata");

        cbVrstaRezultata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbVrstaRezultata.setSelectedIndex(-1);

        jLabel4.setText("Rezultat se odnosi na eksperiment:");

        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sačuvaj rezultat");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        lblEksperiment.setText("jLabel5");

        cbEksperimenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEksperimentiActionPerformed(evt);
            }
        });

        txtOpisRez.setColumns(20);
        txtOpisRez.setRows(5);
        jScrollPane1.setViewportView(txtOpisRez);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblEksperiment))
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(btnOtkazi))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                            .addComponent(btnSacuvaj))
                        .addComponent(cbVrstaRezultata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNazivRez)
                        .addComponent(cbEksperimenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEksperimenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEksperiment))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNazivRez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVrstaRezultata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnSacuvaj))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        rezultat.setEksperiment((Eksperiment)cbEksperimenti.getSelectedItem());
        rezultat.setNaziv(txtNazivRez.getText());
        rezultat.setOpis(txtOpisRez.getText());
        rezultat.setVrstaRezultata((VrstaRezultata) cbVrstaRezultata.getSelectedItem());
        
        if(rezultat.getNaziv().isEmpty()||rezultat.getNaziv().length()>100){
            JOptionPane.showMessageDialog(this, "Naziv je neispravan, duzi od 100 karaktera ili prazan!");
        }
        else if(rezultat.getOpis().isEmpty()||rezultat.getOpis().length()>255){
            JOptionPane.showMessageDialog(this, "Opis je neispravan, duzi od 255 karaktera ili prazan!");
        }
        else if(rezultat.getVrstaRezultata()==null){
            JOptionPane.showMessageDialog(this, "Selektujte vrstu rezultata!");
        }
        else{
            ubaciUBazu(rezultat);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void cbEksperimentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEksperimentiActionPerformed
        lblEksperiment.setText(cbEksperimenti.getSelectedItem().toString());
    }//GEN-LAST:event_cbEksperimentiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cbEksperimenti;
    private javax.swing.JComboBox<Object> cbVrstaRezultata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEksperiment;
    private javax.swing.JTextField txtNazivRez;
    private javax.swing.JTextArea txtOpisRez;
    // End of variables declaration//GEN-END:variables

    private void setUp(boolean flag) {
        txtOpisRez.setLineWrap(true); 
        txtOpisRez.setWrapStyleWord(true);
        cbVrstaRezultata.setModel(new DefaultComboBoxModel<>(VrstaRezultata.values()));
        cbVrstaRezultata.setSelectedIndex(-1);
        String[] argumenti = {"",""};
        try {
            Controller.getInstance().pretragaEksperimenata(argumenti);
            
        } catch (Exception ex) {
            Logger.getLogger(FrmRezultat.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(rezultat.getId()!=0){
            txtNazivRez.setText(rezultat.getNaziv());
            txtOpisRez.setText(rezultat.getOpis());
            cbVrstaRezultata.setSelectedItem(rezultat.getVrstaRezultata());
            txtNazivRez.setEditable(flag);
            txtOpisRez.setEditable(flag);
            cbVrstaRezultata.setEnabled(flag);
            btnSacuvaj.setVisible(flag);
        }
    }

    private void ubaciUBazu(Rezultat rezultat) {
        
        if(rezultat.getId()==0){
            try {
            Controller.getInstance().kreirajRezultat(rezultat);
            
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        
        }else{
            try {
                Controller.getInstance().izmeniRezultat(rezultat);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
        
    }
    public void kreirajRezultat(boolean flag) throws Exception{
        if(flag){
                JOptionPane.showMessageDialog(this, "Uspešno kreiran rezultat! ");
                Controller.getInstance().setFrmRezultat(null);
                dispose();
            }else{
              JOptionPane.showMessageDialog(this, "Greška pri kreiranju rezultata");
              Controller.getInstance().setFrmRezultat(null);
              dispose();
            }
    }
    public void izmeniRezultat(boolean flag) throws Exception{
        if(flag){
            JOptionPane.showMessageDialog(this, "Uspešna izmena rezultata!");
            Controller.getInstance().setFrmRezultat(null);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Neuspešna izmena rezultata!");
            Controller.getInstance().setFrmRezultat(null);
            dispose();
        }
    }
    public void namestiCb(List<Eksperiment> eksperimenti){
        cbEksperimenti.setModel(new DefaultComboBoxModel<>( eksperimenti.toArray()));
        Eksperiment eksperimentSelektovani = new Eksperiment();
        for(Eksperiment eksp : eksperimenti){
            if(eksperiment.getId() == eksp.getId()){
                eksperimentSelektovani = eksp;
            }
        }
        cbEksperimenti.setSelectedItem(eksperimentSelektovani);
        lblEksperiment.setText(eksperiment.toString());
    }
}
